### ISSUE TITLE
Can't show anything 

### ISSUE THREAD

**Issue by LuSoSmartDev** [eramudeep/react-native-ecommerce#1]
I cloned the source and build it success, but nothing showing. I guessed that the import { createStore, applyMiddleware } from "redux" is deprecated. Could you help to run it again ?

**Comment by eramudeep** [comment]
> I cloned the source and build it success, but nothing showing. I guessed that the import { createStore, applyMiddleware } from "redux" is deprecated. Could you help to run it again ?

can you please debug and check log errors?
the application was working seamlessly before.

**Comment by Abinash018** [comment]
no it is not working

**Comment by Abinash018** [comment]
**i think some library is depreceted**

**Comment by eramudeep** [comment]
Bugs are fixed please check and let me know.
